apiVersion: apps/v1
kind: Deployment
metadata:
  name: profils-deployment
spec:
  selector:
    matchLabels:
      app: profils-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: profils-mysql
    spec:
      containers:
        - name: profils
          image: hatembd/profils
          ports:
            - containerPort: 8200
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password