kind: Service
apiVersion: v1
metadata:
  name: app-server-service
spec:
  selector:
    app: app-server
  ports:
  - protocol: TCP
    port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
spec:
  selector:
    matchLabels:
      app: app-server
  replicas: 1
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: app-server
        image: profil-service:1.0
        ports:
        - containerPort: 8080

