kind: Service
apiVersion: v1
metadata:
  name: profil-service
spec:
  selector:
    app: profil-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profil-service
spec:
  selector:
    matchLabels:
      app: profil-service
  replicas: 1
  template:
    metadata:
      labels:
        app: profil-service
    spec:
      containers:
        - name: profil-service
          image: profil-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: profil-db-config
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: profil-db-config
                  key: host
