apiVersion: v1
kind: Service
metadata:
  labels:
    app: profildb
  name: profildb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: profildb
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profildb
  labels:
    app: profildb
spec:
  selector:
    matchLabels:
      app: profildb
  replicas: 1
  template:
    metadata:
      labels:
        app: profildb
      name: profildb-service


    spec:
      containers:
        - image: mongo:latest
          name: profildb

          ports:
            - containerPort: 27017
              name: profildb
